[2023-09-27 13:57:39] [31merror[39m uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 13:59:02] [31merror[39m uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 13:59:05] [31merror[39m uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 13:59:11] [31merror[39m uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 13:59:16] [31merror[39m uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 13:59:23] [31merror[39m uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 13:59:38] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:45
            ? res.send({ msg: 'You have been Logged Out' });
            ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 13:59:43] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:45
            ? res.send({ msg: 'You have been Logged Out' })
            ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 13:59:45] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:45
            ? res.send({ msg: 'You have been Logged Out' })
            ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 13:59:48] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:45
            ? res.send({ msg: 'You have been Logged Out' })
            ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 13:59:52] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:45
            ? res.send({ msg: 'You have been Logged Out' })
            ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 13:59:54] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:45
            ? res.send({ msg: 'You have been Logged Out' })
            ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:00:06] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:44
        if (logout) ? res.send({ msg: 'You have been Logged Out' })
                    ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:00:10] [31merror[39m uncaughtException: Unexpected token '?'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:44
        if (logout) ? res.send({ msg: 'You have been Logged Out' }) : res.send({ msg: 'Error' });
                    ^

SyntaxError: Unexpected token '?'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:00:42] [31merror[39m uncaughtException: Route.put() requires a callback function but got a [object Object]
Error: Route.put() requires a callback function but got a [object Object]
    at Route.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as put] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 14:01:29] [31merror[39m uncaughtException: Route.get() requires a callback function but got a [object Object]
Error: Route.get() requires a callback function but got a [object Object]
    at Route.<computed> [as get] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:211:15)
    at proto.<computed> [as get] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:17:33)
[2023-09-27 14:02:36] [33minfo[39m Server running on port 8081
[2023-09-27 14:02:36] [33minfo[39m DB Connected
[2023-09-27 14:03:06] [33minfo[39m Server running on port 8081
[2023-09-27 14:03:06] [33minfo[39m DB Connected
[2023-09-27 14:03:07] [33minfo[39m Server running on port 8081
[2023-09-27 14:03:07] [33minfo[39m DB Connected
[2023-09-27 14:03:11] [33minfo[39m Server running on port 8081
[2023-09-27 14:03:11] [33minfo[39m DB Connected
[2023-09-27 14:03:25] [33minfo[39m Server running on port 8081
[2023-09-27 14:03:25] [33minfo[39m DB Connected
[2023-09-27 14:03:26] [31merror[39m uncaughtException: missing ) after argument list
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:48
            res.send.status(({ msg: 'Error' });
                                             ^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:03:27] [33minfo[39m Server running on port 8081
[2023-09-27 14:03:27] [33minfo[39m DB Connected
[2023-09-27 14:03:31] [33minfo[39m Server running on port 8081
[2023-09-27 14:03:31] [33minfo[39m DB Connected
[2023-09-27 14:03:41] [33minfo[39m Server running on port 8081
[2023-09-27 14:03:41] [33minfo[39m DB Connected
[2023-09-27 14:04:03] [33minfo[39m Server running on port 8081
[2023-09-27 14:04:03] [33minfo[39m DB Connected
[2023-09-27 14:04:06] [33minfo[39m Server running on port 8081
[2023-09-27 14:04:06] [33minfo[39m DB Connected
[2023-09-27 14:04:11] [31merror[39m uncaughtException: missing ) after argument list
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:46
            res.status(send({ msg: 'You have been Logged Out' });
                                                               ^

SyntaxError: missing ) after argument list
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:13] [31merror[39m uncaughtException: Unexpected identifier
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:46
            res.status(200)send({ msg: 'You have been Logged Out' });
                           ^^^^

SyntaxError: Unexpected identifier
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:14] [33minfo[39m Server running on port 8081
[2023-09-27 14:04:14] [33minfo[39m DB Connected
[2023-09-27 14:04:31] [33minfo[39m Server running on port 8081
[2023-09-27 14:04:31] [33minfo[39m DB Connected
[2023-09-27 14:04:34] [31merror[39m uncaughtException: Unexpected token ')'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:50
    });
     ^

SyntaxError: Unexpected token ')'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:37] [31merror[39m uncaughtException: Unexpected token ')'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:49
    });
     ^

SyntaxError: Unexpected token ')'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:38] [31merror[39m uncaughtException: Unexpected token ')'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:50
    });
     ^

SyntaxError: Unexpected token ')'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:43] [31merror[39m uncaughtException: Unexpected token ')'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:49
    });
     ^

SyntaxError: Unexpected token ')'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:48] [31merror[39m uncaughtException: Unexpected token ')'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:49
    });
     ^

SyntaxError: Unexpected token ')'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:50] [31merror[39m uncaughtException: Unexpected token ')'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:50
    });
     ^

SyntaxError: Unexpected token ')'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:04:53] [33minfo[39m Server running on port 8081
[2023-09-27 14:04:53] [33minfo[39m DB Connected
[2023-09-27 14:04:57] [33minfo[39m Server running on port 8081
[2023-09-27 14:04:57] [33minfo[39m DB Connected
[2023-09-27 14:05:01] [33minfo[39m Server running on port 8081
[2023-09-27 14:05:01] [33minfo[39m DB Connected
[2023-09-27 14:08:51] [31merror[39m uncaughtException: listen EADDRINUSE: address already in use :::8081
Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at Function.listen (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\app.js:23:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
[2023-09-27 14:08:56] [33minfo[39m Server running on port 8081
[2023-09-27 14:08:57] [33minfo[39m DB Connected
[2023-09-27 14:13:05] [31merror[39m uncaughtException: Unexpected token ')'
C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:27
        const token = await generarJWT( user.);
                                             ^

SyntaxError: Unexpected token ')'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\routes\authenticate.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
[2023-09-27 14:13:10] [33minfo[39m Server running on port 8081
[2023-09-27 14:13:10] [33minfo[39m DB Connected
[2023-09-27 14:13:11] [33minfo[39m Server running on port 8081
[2023-09-27 14:13:11] [33minfo[39m DB Connected
[2023-09-27 14:13:23] [33minfo[39m Server running on port 8081
[2023-09-27 14:13:23] [33minfo[39m DB Connected
[2023-09-27 14:13:47] [33minfo[39m Server running on port 8081
[2023-09-27 14:13:47] [33minfo[39m DB Connected
[2023-09-27 14:15:16] [33minfo[39m Server running on port 8081
[2023-09-27 14:15:16] [33minfo[39m DB Connected
[2023-09-27 14:15:18] [33minfo[39m Server running on port 8081
[2023-09-27 14:15:18] [33minfo[39m DB Connected
[2023-09-27 14:15:23] [33minfo[39m Server running on port 8081
[2023-09-27 14:15:23] [33minfo[39m DB Connected
[2023-09-27 14:15:41] [33minfo[39m Server running on port 8081
[2023-09-27 14:15:41] [33minfo[39m DB Connected
[2023-09-27 14:15:45] [33minfo[39m Server running on port 8081
[2023-09-27 14:15:45] [33minfo[39m DB Connected
[2023-09-27 14:16:37] [33minfo[39m Server running on port 8081
[2023-09-27 14:16:37] [33minfo[39m DB Connected
[2023-09-27 14:16:59] [33minfo[39m Server running on port 8081
[2023-09-27 14:16:59] [33minfo[39m DB Connected
[2023-09-27 14:18:23] [33minfo[39m Server running on port 8081
[2023-09-27 14:18:23] [33minfo[39m DB Connected
[2023-09-27 14:19:19] [33minfo[39m Server running on port 8081
[2023-09-27 14:19:19] [33minfo[39m DB Connected
[2023-09-27 14:20:01] [31merror[39m uncaughtException: jwt is not defined
ReferenceError: jwt is not defined
    at logout (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:45:5)
    at Layer.handle [as handle_request] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:144:13)
    at validarJWT (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\middlewares\validar-jwt.js:19:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-27 14:20:43] [33minfo[39m Server running on port 8081
[2023-09-27 14:20:43] [33minfo[39m DB Connected
[2023-09-27 14:21:52] [33minfo[39m Server running on port 8081
[2023-09-27 14:21:52] [33minfo[39m DB Connected
[2023-09-27 14:21:54] [33minfo[39m Server running on port 8081
[2023-09-27 14:21:54] [33minfo[39m DB Connected
[2023-09-27 14:21:56] [33minfo[39m Server running on port 8081
[2023-09-27 14:21:56] [33minfo[39m DB Connected
[2023-09-27 14:21:59] [33minfo[39m Server running on port 8081
[2023-09-27 14:21:59] [33minfo[39m DB Connected
[2023-09-27 14:22:11] [33minfo[39m Server running on port 8081
[2023-09-27 14:22:12] [33minfo[39m DB Connected
[2023-09-27 14:22:17] [33minfo[39m Server running on port 8081
[2023-09-27 14:22:17] [33minfo[39m DB Connected
[2023-09-27 14:23:18] [31merror[39m uncaughtException: jwt is not defined
ReferenceError: jwt is not defined
    at logout (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\controllers\auth-controller.js:46:5)
    at Layer.handle [as handle_request] (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\node_modules\express\lib\router\route.js:144:13)
    at validarJWT (C:\Users\soosa\OneDrive\Escritorio\Estacionamiento\src\middlewares\validar-jwt.js:19:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
